"""empty message

Revision ID: 12039bc871b5
Revises: f6b6a5555a56
Create Date: 2020-04-29 19:07:39.985592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12039bc871b5'
down_revision = 'f6b6a5555a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('location_room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player')
    # ### end Alembic commands ###
