"""empty message

Revision ID: f6b6a5555a56
Revises: 
Create Date: 2020-04-29 18:47:04.540756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b6a5555a56'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('exit_north_room_id', sa.Integer(), nullable=True),
    sa.Column('exit_south_room_id', sa.Integer(), nullable=True),
    sa.Column('exit_west_room_id', sa.Integer(), nullable=True),
    sa.Column('exit_east_room_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room')
    # ### end Alembic commands ###
